apiVersion: v1
kind: Service
metadata:
  name: hello-flask-service
spec:
  selector:
    app: hello-flask-app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalamcer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask-app
spec:
  selector:
    matchLabels:
      app: hello-flask-app
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-flask-app
    spec:
      containers:
      - name: hello-flask-app
        image: 654654490827.dkr.ecr.eu-west-2.amazonaws.com/hello-flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80